// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsMjCWaiI-FSvRn_bemDVNnnfMcP0qkE',
    appId: '1:602749056255:web:1c0e82df4328a1a438c8ca',
    messagingSenderId: '602749056255',
    projectId: 'eventia-6f8ef',
    authDomain: 'eventia-6f8ef.firebaseapp.com',
    storageBucket: 'eventia-6f8ef.firebasestorage.app',
    measurementId: 'G-DYM3MTKNX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_VCWy22PVffLPHaiJf71mcnVxlAGc8c',
    appId: '1:602749056255:android:3806d96c3a130eae38c8ca',
    messagingSenderId: '602749056255',
    projectId: 'eventia-6f8ef',
    storageBucket: 'eventia-6f8ef.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUsMjCWaiI-FSvRn_bemDVNnnfMcP0qkE',
    appId: '1:602749056255:web:d692c00b118c4d5d38c8ca',
    messagingSenderId: '602749056255',
    projectId: 'eventia-6f8ef',
    authDomain: 'eventia-6f8ef.firebaseapp.com',
    storageBucket: 'eventia-6f8ef.firebasestorage.app',
    measurementId: 'G-4SRL8SYTQX',
  );
}
